version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: chitolpitha-app
    command: npm run dev
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - ${PORT}:${PORT}
    environment:
      - NODE_ENV=development
    env_file:
      - .env
    depends_on:
      - db
      - redis
      # - cassandra
      # - rabbitmq
      # - neo4j
  db:
    image: mongo:4.4.1
    container_name: chitolpitha-db
    volumes:
      - ./volumes/db:/data
    environment:
      MONGO_INITDB_ROOT_USERNAME: chitolpitha
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: chitolpitha
    ports:
      - 27016:27017

  redis:
    image: 'redis/redis-stack:latest'
    container_name: chitolpitha-cache
    restart: unless-stopped
    # command: redis-server
    volumes:
      - ./volumes/redis-stack/data:/data
      - ./volumes/redis-stack/redis-conf:/usr/local/etc/redis/redis.conf
    # environment:
    #   - REDIS_REPLICATION_MODE=master
    # deploy:
    #   replicas: 1
    #   restart_policy:
    #     condition: on-failure
    ports:
      - ${REDIS_PORT:-6364}:6379

  redis-commander:
    container_name: chitolpitha-cache-admin
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - ${REDIS_COMMANDER_PORT:-8389}:8081

  nats:
    image: nats:latest
    container_name: chitolpitha-nats
    ports:
      - '4222:4222'
      - '8222:8222'

  localstack:
    image: localstack/localstack
    container_name: "${LOCALSTACK_DOCKER_NAME-chitolpitha-cloud}"  
    environment:
      - SERVICES=s3,dynamodb
      - DEFAULT_REGION=us-east-1
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=admin
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR-}
      - DISABLE_CORS_CHECKS=1
      - S3_DIR=/tmp/s3-buckets
      - S3_BUCKET=mybucket
      - S3_PATH=/chitolpitha-uploads
      - DATA_DIR=./volumes/localstack/data
      - PORT_WEB_UI=9000
      - START_WEB=1
    ports:
      - '4566:4566'
      - '4571:4571'
    volumes:
      - "${TMPDIR:-/tmp}/localstack:/tmp/localstack"
      - '/var/run/docker.sock:/var/run/docker.sock'

  # cassandra:
  #   image: cassandra:3.11
  #   container_name: chitolpitha-write-db
  #   ports:
  #     - 9042:9042

  # rabbitmq:
  #   image: rabbitmq:3-management
  #   container_name: chitolpitha-message-queue
  #   ports:
  #     - 5672:5672
  #     - 15672:15672
  # neo4j:
  #   image: neo4j:3.5
  #   container_name: chitolpitha-graphdb
  #   ports:
  #     - 7474:7474
  #     - 7687:7687
